### ISSUE TITLE
How to do anything with file

### ISSUE THREAD

**Issue by BaconBoys01** [0x77ff/Byte-Stealer#12]
So ive got everything in with my webhook i just need to know how i get it disgiused as the image i have ive tried resource hacker and a couple other things but im not sure what to do next or if i need to convert something to an .exe

**Comment by toxinsfx** [comment]
use ur brain :3

**Comment by toxinsfx** [comment]
> So ive got everything in with my webhook i just need to know how i get it disgiused as the image i have ive tried resource hacker and a couple other things but im not sure what to do next or if i need to convert something to an .exe

btw ur getting doxxed

**Comment by 0x77ff** [comment]
> So ive got everything in with my webhook i just need to know how i get it disgiused as the image i have ive tried resource hacker and a couple other things but im not sure what to do next or if i need to convert something to an .exe

this aint am image logger js

**Comment by BaconBoys01** [comment]
:(
