### ISSUE TITLE
Byte-Stealer

### ISSUE THREAD

**Issue by scalap94** [0x77ff/Byte-Stealer#7]
Hi, your work is incredible! 

I have a little problem launching "Logger.exe" 

![image](https://github.com/TurtlesXD/Byte-Stealer/assets/145420374/b0a890e2-828d-4c99-b484-0bbe09300d8a)

However, I followed the installation procedure correctly.

Can u help me? Thanks.

**Comment by TurtlesXD** [comment]
try opening command prompt and run `pip install comtypes pywifi`

**Comment by TurtlesXD** [comment]
* leave encoding empty for utf-8
*
