### ISSUE TITLE
Pyarmor, and two error messages

### ISSUE THREAD

**Issue by glwckiron** [0x77ff/Byte-Stealer#8]
I got an error message on build.exe I'm using the experimental version.  "No module named pyarmor.__main__; 'pyarmor' is a package and cannot be directly executed."

Also in the install packages.bat, I had two error messages not sure if this is part of the process.

ERROR: Could not find a version that satisfies the requirement threading (from versions: none)
ERROR: No matching distribution found for threading

**Comment by 0x77ff** [comment]
This project isn't supported anymore as I have moved on to other things so I wont be able to help,
