### ISSUE TITLE
Python not found!

### ISSUE THREAD

**Issue by RunningOuttaRam** [0x77ff/Byte-Stealer#9]
When I run either the Install-Packages or ConfigLogger it just says that Python is not found. I have python 3.12 and you said that it would work on Python 3.9 and above so I assumed that it would work. How do I fix this problem?

**Comment by RunningOuttaRam** [comment]
nvm I just scrolled through a bunch of closed comments and I saw that you are no longer supporting this project so its alr anyways. Thank you for acknowledging this and feel free to mark this issue as "completed".

**Comment by RunningOuttaRam** [comment]
Last question though, im already knee deep into this in the making of this thread I just want to ask how to uninstall the files that was injected onto my pc? It would be great if you could help me with that Thank You.

**Comment by 0x77ff** [comment]
just delete the zip that was downloaded, The things downloaded in config file are python libraries, meaning you have to delete the libs folder in the python directory to remove them
